import type { NoteEvent, Phrase, Song } from '../audio/types';
import type { CanvasMark, CanvasPoint, CanvasTool, DrawTool, Performer, StampKind, WorldConfig, WorldId } from './canvasTypes';
import { buildRelationshipGraph } from './relationships';
import { WORLD_MAP, WORLDS } from './worlds/config';
export type { CanvasMark, CanvasPoint, CanvasTool, DrawTool, StampKind, WorldConfig, WorldId } from './canvasTypes';
export { WORLD_MAP, WORLDS } from './worlds/config';
export { performFloodFill, cacheFillMask, recolorFillDataUrl } from './floodFill';

const clamp=(v:number,lo=0,hi=1)=>Math.max(lo,Math.min(hi,v));
const rng=(seed:number)=>()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};
const midiFreq=(m:number)=>440*Math.pow(2,(m-69)/12);
const midiPitch=(m:number)=>{const n=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'],x=Math.round(m);return`${n[((x%12)+12)%12]}${Math.floor(x/12)-1}`;};
function event(midi:number,timeOffset:number,duration:number,velocity:number,extra:Partial<NoteEvent>={}):NoteEvent{return{pitch:midiPitch(midi),frequency:midiFreq(midi),timeOffset:Math.max(0,timeOffset),duration:Math.max(.04,duration),velocity:clamp(velocity,.05,.9),...extra};}
export function markBounds(mark:CanvasMark){if(mark.bounds)return mark.bounds;if(mark.tool==='fill')return{minX:0,maxX:1,minY:0,maxY:1};const pts=mark.points.length?mark.points:[{x:.5,y:.5}];let minX=1,maxX=0,minY=1,maxY=0;for(const p of pts){minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y);}const pad=(mark.tool==='stamp'||mark.tool==='boom'?.04:.012)*mark.size;return{minX:clamp(minX-pad),maxX:clamp(maxX+pad),minY:clamp(minY-pad),maxY:clamp(maxY+pad)};}
function sample(mark:CanvasMark,count:number){const pts=(mark.points.length?mark.points:[{x:.5,y:.5}]).slice().sort((a,b)=>a.x-b.x);if(pts.length<=count)return pts;return Array.from({length:count},(_,i)=>pts[Math.round(i*(pts.length-1)/(count-1))]);}
function smooth(mark:CanvasMark,count:number){const pts=sample(mark,Math.max(count*2,count));const s=pts.map((p,i)=>{const a=pts[Math.max(0,i-1)],c=pts[Math.min(pts.length-1,i+1)];return{x:p.x,y:clamp(a.y*.2+p.y*.6+c.y*.2)};});if(s.length<=count)return s;return Array.from({length:count},(_,i)=>s[Math.round(i*(s.length-1)/(count-1))]);}
function totalDuration(w:WorldConfig){return w.totalBeats*60/w.tempo;}
function chord(w:WorldConfig,absolute:number,total:number){const i=Math.floor(clamp(absolute/total,0,.999)*Math.max(w.progression.length,Math.round(w.totalBeats/4)));return w.progression[i%w.progression.length];}
function nearest(w:WorldConfig,target:number,absolute:number,total:number,chordBias=false,previous?:number,maxLeap=7){const ds=chordBias?chord(w,absolute,total):w.scale,c:number[]=[];for(let o=-3;o<=4;o++)for(const d of ds)c.push(w.key+d+o*12);c.sort((a,b)=>Math.abs(a-target)-Math.abs(b-target));if(previous===undefined)return c[0];const near=c.filter(x=>Math.abs(x-previous)<=maxLeap);return(near.length?near:c).sort((a,b)=>Math.abs(a-target)-Math.abs(b-target))[0];}
function targetMidi(w:WorldConfig,p:Performer,y:number){return w.key+(p.octave-4)*12+(0.5-clamp(y))*18;}
function baseExtra(mark:CanvasMark,p:Performer,i:number,pt:CanvasPoint,production:NoteEvent['production']='dry'):Partial<NoteEvent>{return{bank:p.bank,program:p.program,fallbackProgram:p.fallbackProgram,channelIndex:i,channelRole:p.role,tone:p.tone,production:production??p.production??'dry',sourceMarkId:mark.id,canvasX:pt.x,canvasY:pt.y,sourceTool:mark.tool,pan:p.pan,room:p.room,echo:p.echo,drive:p.drive};}
function drumEvents(mark:CanvasMark,w:WorldConfig,p:Performer,total:number,i:number){const beat=60/w.tempo,b=markBounds(mark),r=rng(mark.seed),notes=p.drumNotes?.length?p.drumNotes:[36,38,42],out:NoteEvent[]=[];const hit=(t:number,k:number,v=.48,pt?:CanvasPoint)=>out.push(event(48,t,beat*.13,v,{...baseExtra(mark,p,i,pt||{x:b.minX+t/total,y:.5},mark.tool==='boom'?'bloom':'dry'),drumMidi:notes[k%notes.length]}));if(mark.tool==='fill'){for(let t=0,k=0;t<total;t+=beat*.5,k++)if(k%4!==3||r()>.35)hit(t,k,.36+(k%4===0?.10:0),{x:t/total,y:.5});return out;}if(mark.tool==='dots'){sample(mark,18).forEach((pt,k)=>hit(Math.max(0,(pt.x-b.minX)*total),k,.43+(k%4===0?.08:0),pt));return out;}if(mark.tool==='spray'){for(let k=0;k<12+Math.round(mark.size*5);k++){const x=b.minX+r()*Math.max(.03,b.maxX-b.minX),pt={x,y:b.minY+r()*Math.max(.05,b.maxY-b.minY)};hit((x-b.minX)*total,k,.28+r()*.15,pt);}return out;}const pattern=mark.tool==='boom'?[0,.18,.36,.62,.9,1.2]:mark.tool==='stamp'?[0,.5,1.25,1.5,2.25]:sample(mark,9).map(pt=>(pt.x-b.minX)*total/beat);pattern.forEach((x,k)=>hit(x*beat,k,.48+(k===0?.10:0),sample(mark,9)[k]||mark.points[0]));return out;}
function melodicLine(mark:CanvasMark,w:WorldConfig,p:Performer,total:number,i:number,opts:{count:number;step:number;dur:number;maxLeap:number;legato?:boolean;chordBias?:boolean}){const b=markBounds(mark),pts=smooth(mark,opts.count),out:NoteEvent[]=[];let prev:number|undefined;for(let k=0;k<pts.length;k++){const pt=pts[k],abs=pt.x*total,m=nearest(w,targetMidi(w,p,pt.y),abs,total,opts.chordBias||k===0||k===pts.length-1,prev,opts.maxLeap);prev=m;const t=Math.max(0,(pt.x-b.minX)*total),next=pts[k+1],gap=next?Math.max(.08,(next.x-pt.x)*total):opts.dur;const dur=opts.legato?Math.min(opts.dur,gap*1.12):Math.min(opts.dur,gap*.78);const e=event(m,t,Math.max(.08,dur),.43+(k%4===0?.08:0),{...baseExtra(mark,p,i,pt,opts.legato?'smear':'dry'),articulation:opts.legato?'legato':k%4===0?'accent':'tenuto',motion:Math.abs((next?.y??pt.y)-pt.y)});if(next&&opts.legato){const nm=nearest(w,targetMidi(w,p,next.y),next.x*total,total,false,m,opts.maxLeap);if(Math.abs(nm-m)<=4)e.glideToFrequency=midiFreq(nm);}out.push(e);}return out;}
function chordEvents(mark:CanvasMark,w:WorldConfig,p:Performer,total:number,i:number,count=2,fast=false){const beat=60/w.tempo,b=markBounds(mark),pts=sample(mark,count),out:NoteEvent[]=[];for(let k=0;k<Math.max(1,pts.length);k++){const pt=pts[k]||mark.points[0]||{x:.5,y:.5},ch=chord(w,pt.x*total,total),base=w.key+(p.octave-4)*12,t=Math.max(0,(pt.x-b.minX)*total);ch.slice(0,fast?3:4).forEach((d,j)=>out.push(event(base+d,t+j*(fast?.045:.025),beat*(fast?.55:1.15),.38+(j===0?.07:0),{...baseExtra(mark,p,i,pt,fast?'dry':'bloom'),articulation:fast?'accent':'tenuto'})));}return out;}
function textureEvents(mark:CanvasMark,w:WorldConfig,p:Performer,total:number,i:number){const beat=60/w.tempo,b=markBounds(mark),r=rng(mark.seed),out:NoteEvent[]=[];const count=mark.tool==='spray'?8:mark.tool==='fill'?Math.ceil(total/(beat*2)):mark.tool==='boom'?4:3;for(let k=0;k<count;k++){const x=mark.tool==='fill'?Math.min(.98,(k*beat*2)/total):b.minX+r()*Math.max(.03,b.maxX-b.minX),y=mark.tool==='fill'?.35+r()*.3:b.minY+r()*Math.max(.05,b.maxY-b.minY),pt={x,y},m=nearest(w,targetMidi(w,p,y),x*total,total,k%2===0),t=mark.tool==='fill'?k*beat*2:Math.max(0,(x-b.minX)*total);out.push(event(m,t,beat*(mark.tool==='boom'?2.8:mark.tool==='fill'?2.5:1.4+r()),.25+r()*.12,{...baseExtra(mark,p,i,pt,'bloom'),articulation:'legato',motion:.18}));}return out;}

function flamencoTechnique(mark:CanvasMark,w:WorldConfig,p:Performer,total:number,i:number){const beat=60/w.tempo,pt=mark.points[0]||{x:.5,y:.5},base=w.key+(p.octave-4)*12,ch=chord(w,pt.x*total,total),choice=w.stamps.find(s=>s.id===mark.stampKind),id=choice?.technique||mark.stampKind||'rasgueado',out:NoteEvent[]=[];const chordalGuitar=(p.name==='guitar'||p.name==='falseta')&&['rasgueado','abanico','golpe','llamada','remate'].includes(id);const add=(m:number,t:number,d:number,v:number,art:NoteEvent['articulation']='accent')=>out.push(event(m,t,d,v,{...baseExtra(mark,p,i,pt,id==='abanico'?'smear':'dry'),...(chordalGuitar?{bank:'flamenco_strum' as const,program:0}:{}),articulation:art,technique:id}));if(p.role==='drums'){const notes=p.drumNotes||[39,37,54],pat=id==='remate'?[0,.25,.5,.75,1,1.25]:id==='llamada'?[0,.5,.75,1]:[0,.5,1,1.5];pat.forEach((b,k)=>out.push(event(48,b*beat,beat*.12,.5+(k===0?.1:0),{...baseExtra(mark,p,i,pt),drumMidi:notes[k%notes.length],technique:id})));return out;}if(id==='picado'){let prev:number|undefined;for(let k=0;k<8;k++){const m=nearest(w,base+k,pt.x*total,total,k===7,prev,3);prev=m;add(m,k*beat*.18,beat*.16,.48,'staccato');}}else if(id==='alzapua'){[0,7,0,3,7,3].forEach((d,k)=>add(base+d,k*beat*.24,beat*.20,.5,k%3===0?'accent':'staccato'));}else if(id==='golpe'){add(base+ch[0],0,beat*.16,.66,'accent');add(base+ch[1],beat*.08,beat*.12,.38,'staccato');}else if(id==='llamada'){[0,1,2,0].forEach((x,k)=>add(base+ch[x%ch.length],k*beat*.42,beat*.30,.58,k===0?'accent':'marcato'));}else if(id==='remate'){[0,2,1,0].forEach((x,k)=>add(base+ch[x%ch.length],k*beat*.26,beat*.22,.55+k*.02,'accent'));}else{const pattern=id==='abanico'?[0,.11,.22,.38,.49,.60]:[0,.07,.14,.21,.36,.43];pattern.forEach((t,k)=>ch.slice(0,3).forEach((d,j)=>add(base+d,t*beat+j*.025,beat*.34,.38+(k===0?.08:0),id==='rasgueado'?'marcato':'accent')));}return out;}
function tangoTechnique(mark:CanvasMark,w:WorldConfig,p:Performer,total:number,i:number){const beat=60/w.tempo,pt=mark.points[0]||{x:.5,y:.5},base=w.key+(p.octave-4)*12,ch=chord(w,pt.x*total,total),choice=w.stamps.find(s=>s.id===mark.stampKind),id=choice?.technique||mark.stampKind||'marcato4',out:NoteEvent[]=[];const addChord=(t:number,v=.5,d=beat*.42)=>ch.slice(0,3).forEach((x,j)=>out.push(event(base+x,t+j*.018,d,v-(j*.025),{...baseExtra(mark,p,i,pt,id==='arrastre'?'smear':'dry'),articulation:id.startsWith('marcato')?'marcato':'accent',technique:id})));if(id==='marcato2'){[0,2].forEach(b=>addChord(b*beat,.54,beat*.6));}else if(id==='marcato4'){[0,1,2,3].forEach(b=>addChord(b*beat,.49+(b===0?.07:0),beat*.42));}else if(id==='sincopa'){[0,.75,1.5,2.75].forEach((b,k)=>addChord(b*beat,.48+(k%2?.08:0),beat*.38));}else if(id==='arrastre'){const target=base+ch[0];for(let k=0;k<4;k++){const m=target-5+k*2;const e=event(m,k*beat*.12,beat*.26,.38+k*.05,{...baseExtra(mark,p,i,pt,'smear'),articulation:'legato',technique:id});if(k<3)e.glideToFrequency=midiFreq(m+2);out.push(e);}addChord(beat*.52,.58,beat*.7);}else if(id==='milonga'){[0,.75,1.5,2.0,2.75,3.5].forEach((b,k)=>addChord(b*beat,.44+(k%3===0?.07:0),beat*.28));}else if(id==='yumba'){[0,1,2,3].forEach((b,k)=>addChord(b*beat,k%2===0?.58:.40,beat*(k%2===0?.62:.30)));}else{[0,7,3,7,0,10].forEach((d,k)=>out.push(event(base+d,k*beat*.34,beat*.48,.45+(k===0?.08:0),{...baseExtra(mark,p,i,pt,'dry'),articulation:'tenuto',technique:id})));}return out;}

function eventsForMark(mark:CanvasMark,w:WorldConfig,total:number){const p=w.palette[mark.paletteIndex%w.palette.length],i=mark.paletteIndex%w.palette.length,beat=60/w.tempo;if(mark.tool==='stamp'&&w.id==='flamenco')return flamencoTechnique(mark,w,p,total,i);if(mark.tool==='stamp'&&w.id==='tango')return tangoTechnique(mark,w,p,total,i);if(p.role==='drums')return drumEvents(mark,w,p,total,i);if(mark.tool==='fill'){if(p.role==='bass')return melodicLine({...mark,points:Array.from({length:Math.max(5,Math.round(total/beat/2))},(_,k)=>({x:k/Math.max(4,Math.round(total/beat/2)-1),y:.62+(k%3)*.04}))},w,p,total,i,{count:Math.max(5,Math.round(total/beat/2)),step:beat,dur:beat*.8,maxLeap:4,chordBias:true});if(p.role==='harmony')return chordEvents({...mark,points:Array.from({length:Math.max(3,Math.round(total/beat/4))},(_,k)=>({x:k/Math.max(2,Math.round(total/beat/4)-1),y:.5}))},w,p,total,i,Math.max(3,Math.round(total/beat/4)));return textureEvents(mark,w,p,total,i);}if(p.role==='harmony')return mark.tool==='crayon'?melodicLine(mark,w,p,total,i,{count:6,step:beat*.5,dur:beat*.75,maxLeap:4,legato:true,chordBias:true}):chordEvents(mark,w,p,total,i,mark.tool==='boom'?1:mark.tool==='stamp'?1:3,mark.tool==='boom');if(p.role==='bass')return melodicLine(mark,w,p,total,i,{count:mark.tool==='dots'?7:5,step:beat*.5,dur:beat*.8,maxLeap:4,legato:mark.tool==='crayon',chordBias:true});if(p.role==='texture'||p.role==='human')return textureEvents(mark,w,p,total,i);return melodicLine(mark,w,p,total,i,{count:mark.tool==='spray'?8:mark.tool==='dots'?7:6,step:beat*(w.id==='salsa_party'||w.id==='zouk'?.25:.5),dur:beat*(mark.tool==='boom'?1.4:.7),maxLeap:w.id==='dreamland'?5:7,legato:mark.tool==='crayon',chordBias:true});}
function phraseFromMark(mark:CanvasMark,w:WorldConfig,total:number,useFrozen=true):Phrase{const b=markBounds(mark),start=b.minX*total,events=useFrozen&&mark.frozenWorldId===w.id&&mark.frozenEvents?.length?mark.frozenEvents.map(e=>({...e})):eventsForMark(mark,w,total);const clean=events.filter(e=>!mark.erasures?.some(h=>Math.hypot((e.canvasX??b.minX)-h.x,(e.canvasY??.5)-h.y)<(h.radius??.05)));const duration=Math.max(.15,...clean.map(e=>e.timeOffset+e.duration));return{id:`phrase_${mark.id}`,sourceMarkId:mark.id,performerIndex:mark.paletteIndex,startTime:start,duration,events:clean,energy:Math.min(1,.3+clean.length/18),density:Math.min(1,clean.length/24)};}
function relationshipEvents(rel:{kind:string;strength:number},source:Phrase,target:Phrase,w:WorldConfig){const out:NoteEvent[]=[];if(!source.events.length||!target.events.length)return out;const base=source.events.slice(0,5),targetStrong=target.events.slice(0,5);if(rel.kind==='harmonize'){base.forEach((e,k)=>{const t=targetStrong[k%targetStrong.length],m=69+12*Math.log2(Math.max(8,t.frequency)/440)+(k%2?3:7);out.push({...e,pitch:midiPitch(m),frequency:midiFreq(m),timeOffset:Math.max(0,(target.startTime+t.timeOffset)-source.startTime+.03),duration:Math.min(e.duration,t.duration*1.1),velocity:e.velocity*.42,relationshipGenerated:true,sourceMarkId:source.sourceMarkId});});}else if(rel.kind==='together'){base.forEach((e,k)=>{const t=targetStrong[k%targetStrong.length];out.push({...e,timeOffset:Math.max(0,(target.startTime+t.timeOffset)-source.startTime),duration:Math.min(e.duration,t.duration),velocity:e.velocity*.38,relationshipGenerated:true});});}else{targetStrong.slice(-2).forEach((t,k)=>{const e=base[k%base.length];out.push({...e,timeOffset:Math.max(0,(target.startTime+t.timeOffset+t.duration)-source.startTime+(60/w.tempo)*.12),duration:e.duration*.7,velocity:e.velocity*.36,relationshipGenerated:true});});}return out;}
export function freezeMark(mark:CanvasMark,worldId:WorldId){const w=WORLD_MAP[worldId],total=totalDuration(w),events=eventsForMark(mark,w,total);return{...mark,frozenWorldId:worldId,frozenEvents:events};}
export function eraseMarkAt(mark:CanvasMark,p:CanvasPoint,worldId:WorldId,radius=.05){if(mark.tool==='fill'){const b=mark.bounds||{minX:0,maxX:1,minY:0,maxY:1};if(p.x<b.minX-radius||p.x>b.maxX+radius||p.y<b.minY-radius||p.y>b.maxY+radius)return mark;const erasures=[...(mark.erasures||[]),{...p,radius}];if(erasures.length>8)return null;return{...mark,erasures};}if(mark.points.some(pt=>Math.hypot(pt.x-p.x,pt.y-p.y)<radius*1.2)){const erasures=[...(mark.erasures||[]),{...p,radius}],frozen=(mark.frozenEvents||[]).filter(e=>Math.hypot((e.canvasX??.5)-p.x,(e.canvasY??.5)-p.y)>=radius*1.1);if(frozen.length===0&&mark.points.filter(pt=>Math.hypot(pt.x-p.x,pt.y-p.y)>=radius).length<2)return null;return{...mark,erasures,frozenEvents:frozen};}return mark;}
export function interpretMark(mark:CanvasMark,worldId:WorldId){const w=WORLD_MAP[worldId],total=totalDuration(w);return phraseFromMark(mark,w,total,true);}
export function interpretCanvas(marks:CanvasMark[],worldId:WorldId):Song{const w=WORLD_MAP[worldId],total=totalDuration(w),phrases=marks.map(m=>phraseFromMark(m,w,total,true)),byId=new Map(phrases.map(p=>[p.sourceMarkId,p]));for(const rel of buildRelationshipGraph(marks,w)){const src=byId.get(rel.sourceId),tar=byId.get(rel.targetId);if(src&&tar){const adds=relationshipEvents(rel,src,tar,w);src.events.push(...adds);src.duration=Math.max(src.duration,...src.events.map(e=>e.timeOffset+e.duration));}}let cursor=0;const sections=w.sections.map((s,idx)=>{const start=cursor,end=idx===w.sections.length-1?total:Math.min(total,cursor+total*s.weight);cursor=end;return{id:`sec_${idx}`,name:s.name,startTime:start,duration:end-start,intensity:s.energy,phrases:phrases.filter(p=>p.startTime<end&&p.startTime+p.duration>=start)};});return{id:`song_${worldId}`,worldId,baseTempo:w.tempo,totalDuration:total,sections};}
export function randomWorld(exclude?:WorldId):WorldId{const pool=exclude?WORLDS.filter(w=>w.id!==exclude):WORLDS;return pool[Math.floor(Math.random()*pool.length)].id;}
