import { SoundFontStudio } from './soundfontStudio';
import type { Phrase, Song, TransportState } from './types';

class Transport {
  private studio:SoundFontStudio|null=null; private song:Song|null=null; private playing=false; private startTime=0; private pausedAt=0; private timer:number|null=null; private frame:number|null=null; private scheduled=new Set<string>(); private listeners=new Set<(s:TransportState)=>void>(); private lookAhead=.18; private scheduledTo=0;
  private init(){if(!this.studio)this.studio=new SoundFontStudio();}
  unlockAudio(){this.init();this.studio!.unlockFromGesture();}
  setSong(song:Song,preservePosition=false,preserveAudition=false){const old=this.song?.totalDuration??0,thisPos=preservePosition&&old>0?Math.min(song.totalDuration,this.currentTime()):0;this.song=song;this.pausedAt=thisPos;this.scheduled.clear();this.scheduledTo=thisPos;if(this.playing){this.stop(false);this.playing=true;this.startTime=(this.studio?.ctx.currentTime??0)-thisPos;this.startLoops();}else if(!preserveAudition)this.studio?.stopTransport();this.emit();}
  private currentTime(){if(!this.song)return 0;if(this.playing&&this.studio)return Math.max(0,Math.min(this.song.totalDuration,this.studio.ctx.currentTime-this.startTime));return this.pausedAt;}
  togglePlay(){if(this.playing)this.pause();else{this.unlockAudio();this.play();}}
  private play(){if(!this.song)return;this.init();this.studio!.resumeTransport();this.playing=true;this.startTime=this.studio!.ctx.currentTime-this.pausedAt;this.scheduledTo=this.pausedAt;this.scheduled.clear();this.startLoops();this.emit();}
  private pause(){if(!this.song||!this.studio)return;this.pausedAt=this.currentTime();this.playing=false;this.clearLoops();this.studio.stopTransport();this.emit();}
  stop(reset=true){if(reset)this.pausedAt=0;else this.pausedAt=this.currentTime();this.playing=false;this.clearLoops();this.scheduled.clear();this.scheduledTo=this.pausedAt;this.studio?.stopTransport();this.emit();}
  seek(time:number){if(!this.song)return;const t=Math.max(0,Math.min(this.song.totalDuration,time)),was=this.playing;this.studio?.stopTransport();this.pausedAt=t;this.scheduled.clear();this.scheduledTo=t;if(was&&this.studio){this.startTime=this.studio.ctx.currentTime-t;}this.emit();}
  auditionPhrase(phrase:Phrase,live=false){this.init();this.studio!.resumeTransport();if(this.song){const sec=this.song.sections.findIndex(s=>phrase.startTime>=s.startTime&&phrase.startTime<s.startTime+s.duration);this.studio!.setStudioState({worldId:this.song.worldId,tempo:this.song.baseTempo,sectionIndex:Math.max(0,sec),sectionEnergy:this.song.sections[Math.max(0,sec)]?.intensity??phrase.energy});}const ordered=phrase.events.slice().sort((a,b)=>a.timeOffset-b.timeOffset);if(!ordered.length)return;let events=ordered;if(live){const last=ordered[ordered.length-1];events=ordered.filter(e=>Math.abs(e.timeOffset-last.timeOffset)<.03).slice(-3);if(!events.length)events=[last];}else{const first=ordered[0].timeOffset;events=ordered.filter(e=>e.timeOffset-first<=1.8).slice(0,18);}const first=Math.min(...events.map(e=>e.timeOffset)),start=this.studio!.ctx.currentTime+.008;for(const e of events)this.studio!.playNote({...e,timeOffset:e.timeOffset-first,duration:live?Math.min(.45,e.duration):e.duration},start+Math.max(0,e.timeOffset-first));}
  private schedule(){if(!this.song||!this.studio||!this.playing)return;const nowSong=this.currentTime();if(nowSong>=this.song.totalDuration){this.stop();return;}const end=Math.min(this.song.totalDuration,Math.max(this.scheduledTo,nowSong)+this.lookAhead);for(const sec of this.song.sections){if(sec.startTime> end||sec.startTime+sec.duration<nowSong-.5)continue;for(const phrase of sec.phrases){for(let i=0;i<phrase.events.length;i++){const e=phrase.events[i],t=phrase.startTime+e.timeOffset;if(t<this.scheduledTo||t>=end)continue;const key=`${phrase.id}:${i}:${t.toFixed(3)}`;if(this.scheduled.has(key))continue;this.scheduled.add(key);this.studio.playNote(e,this.studio.ctx.currentTime+Math.max(0,t-nowSong));}}}this.scheduledTo=end;const secIdx=this.song.sections.findIndex(s=>nowSong>=s.startTime&&nowSong<s.startTime+s.duration);const s=this.song.sections[Math.max(0,secIdx)]??this.song.sections[0];this.studio.setStudioState({worldId:this.song.worldId,tempo:this.song.baseTempo,sectionIndex:Math.max(0,secIdx),sectionEnergy:s?.intensity??.6});}
  private startLoops(){this.clearLoops();this.timer=window.setInterval(()=>this.schedule(),55);const tick=()=>{if(!this.playing)return;this.emit();this.frame=requestAnimationFrame(tick);};this.frame=requestAnimationFrame(tick);this.schedule();}
  private clearLoops(){if(this.timer!==null){clearInterval(this.timer);this.timer=null;}if(this.frame!==null){cancelAnimationFrame(this.frame);this.frame=null;}}
  private snapshot():TransportState{const t=this.currentTime(),idx=this.song?Math.max(0,this.song.sections.findIndex(s=>t>=s.startTime&&t<s.startTime+s.duration)):0,active:string[]=[];if(this.song)for(const s of this.song.sections)for(const p of s.phrases)if(t>=p.startTime&&t<=p.startTime+p.duration)active.push(p.id);return{isPlaying:this.playing,currentTime:t,totalDuration:this.song?.totalDuration??0,currentSectionIndex:idx,activePhraseIds:active};}
  private emit(){const s=this.snapshot();for(const l of this.listeners)l(s);}
  subscribe(fn:(s:TransportState)=>void){this.listeners.add(fn);fn(this.snapshot());return()=>{this.listeners.delete(fn);};}
}
export const transport=new Transport();
